name: ❓ 질문
description: 프로젝트에 대해 궁금한 점이 있을 때 사용하는 템플릿입니다
title: "[질문] "
labels: ["question"]
body:
  - type: textarea
    id: question
    attributes:
      label: 질문 내용
      description: 궁금한 점을 명확하게 작성해주세요
      placeholder: 예: Git 브랜치를 병합하는 방법이 궁금합니다.
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: 관련 맥락
      description: 질문과 관련된 상황이나 배경을 설명해주세요
      placeholder: 예: main 브랜치에서 작업 중인데, 다른 브랜치의 변경사항을 가져오고 싶습니다.

  - type: textarea
    id: tried
    attributes:
      label: 시도해본 것
      description: 이미 시도해본 방법이나 참고한 자료가 있다면 작성해주세요
      placeholder: 예: git pull을 시도했지만 오류가 발생했습니다.

  - type: dropdown
    id: urgency
    attributes:
      label: 긴급도
      description: 답변이 필요한 긴급도를 선택해주세요
      options:
        - 낮음 (여유있게 답변해주세요)
        - 보통
        - 높음 (빠른 답변이 필요합니다)
      default: 1

